Add routing functional, autorization
Y1em/react-burger pull request #5
Opened 2023-03-06 22:20 UTC by Y1em

2023-03-07 01:21 UTC, andryxxa93 requested changes
Здравствуйте! Хорошая работа 👍 
Что понравилось:
- Регулярки записаны в константы
- Роутинг настроен и работает хорошо
- хороший `codestyle`

Что необходимо исправить:
- Авторизация не должна сбрасываться при перезагрузке страницы
- При переходе в личный кабинет активными являются сразу две ссылки - "История заказов" и "Выход". Хотя должна только "Профиль".
<img width="1041" alt="Снимок экрана 2023-03-07 в 04 03 59" src="https://user-images.githubusercontent.com/60173362/223292430-8d68674d-54ba-4bd1-b22b-a8e883bdaa6a.png">

- Сейчас изменить данные юзера можно только если заполнить имя, имейл и пароль, это не верно, необходимо дать возможность изменять данные без пароля.
- `access token` необходимо записывать в куки
- Вы реализовали обновление протухшего токена - это отлично! Но после его обновления необходимо повторять неудавшийся ранее запрос.
- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут /login. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью  return <Redirect to={location?.state?.from || '/'} />; (эти данные записываются в ProtectedRoute, а используются в Login для Redirect)


**Можно лучше**
- Если при отправке данных форм происходит ошибка - желательно её показывать пользователю, чтобы он понимал, что происходит.
- Роуты лучше записывать в константы - это позволит легче их менять в случае необходимости и будет сложнее ошибиться.

Удачных правок!

2023-03-07 01:21 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const user = useSelector((store) => store.authReducer.name);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-07 01:21 UTC, andryxxa93 commented on src/pages/forgot-password.jsx
> +  if (user) {
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-03-07 01:21 UTC, andryxxa93 commented on src/services/reducers/modal.js
> +      localStorage.setItem('currentItem', JSON.stringify(action.items.find((item) => item._id === action.id ? item : null)));
**Можно лучше**
Записывать в `localStorage` текущий ингредиент не нужно. Вполне достаточно записывать в стейт.

2023-03-11 04:30 UTC, Y1em commented
Замечание: "Вы реализовали обновление протухшего токена - это отлично! Но после его обновления необходимо повторять неудавшийся ранее запрос"
При ошибке " jwt expired" происходит обновление и затем повторный запрос

2023-03-11 07:01 UTC, andryxxa93 requested changes
Супер! Вы отлично поработали 👍 
Исправьте пару замечаний и работа будет принята:

- Данные можно изменить только если к данным в форме что-то добавить, а вот если удалить кнопка "Сохранить" не разблокируется. 

https://user-images.githubusercontent.com/60173362/224470162-134e596d-6627-4abc-b5fd-7fc8ea0ecbf8.mov


- Не стоит обновлять токен при каждой попытке изменить данные юзера. Это лишний запрос. Необходимо это делать только если получаете ошибку `jwt expired`. 
Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

- После того как токен обновился неудавшийся запрос проходит - это отлично, но вот следующие запросы падают. 
<img width="1440" alt="Снимок экрана 2023-03-11 в 09 54 35" src="https://user-images.githubusercontent.com/60173362/224470057-88f5f9c6-e323-4294-97e4-e15539c8fc52.png">
<img width="1440" alt="Снимок экрана 2023-03-11 в 09 54 19" src="https://user-images.githubusercontent.com/60173362/224470059-15a50407-f28f-4f09-8093-25095e39c95c.png">

- При переходе в "Личный кабинет" происходит несколько дублирований запросов юзера и токена. 
<img width="1440" alt="Снимок экрана 2023-03-11 в 10 00 11" src="https://user-images.githubusercontent.com/60173362/224470206-65536f60-c2f4-4a95-9cc8-bcbcc3943bca.png">

2023-03-13 05:24 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-21 00:18 UTC, merged